Improve doc coverage (#44)
pchampin/sophia_rs pull request #84
Opened 2020-08-13 18:14 UTC by yever

I added documentation to most public elements in `sophia/`, using
the method described in the issue (#44) of adding `#![deny(missing_docs)]`
to `sophia/src/lib.rs`.

2 doc comments are missing:
- sophia/src/parser/rio_common.rs:72:1
  sophia_api::make_scoped_triple_streaming_mode!(ScopedRioSourceTriple, RioSourceTriple);
- sophia/src/parser/rio_common.rs:112:1
  sophia_api::make_scoped_quad_streaming_mode!(ScopedRioSourceQuad, RioSourceQuad);

I don't know how to add comments to the macro-created types.

2020-08-16 09:40 UTC, yever commented
I have added the last missing doc comments in the `sophia` crate and now the travis build is green :)

This pull request is now ready to be reviewed. @pchampin

2020-08-28 17:02 UTC, pchampin requested changes
Apart from a few things that I would rather rephrase (see comments), this is great. Thanks a lot.

2020-08-28 17:02 UTC, pchampin commented on sophia/src/parser/trig.rs
> +    /// The current base IRI.
```suggestion
    /// The base IRI used by this parser to resolve relative IRI-references.
```

2020-08-28 17:02 UTC, pchampin commented on sophia/src/parser/turtle.rs
> +    /// The current base IRI.
```suggestion
    /// The base IRI used by this parser to resolve relative IRI-references.
```

2020-08-28 17:02 UTC, pchampin commented on sophia/src/parser/turtle.rs
> +/// A wrapper around [`rio_turtle::TurtleError`] the implements [`WithLocation`].
```suggestion
/// A wrapper around [`rio_turtle::TurtleError`] that implements [`WithLocation`].
```

2020-08-28 17:02 UTC, pchampin commented on sophia/src/parser/xml.rs
> +    /// The base IRI.
```suggestion
    /// The base IRI used by this parser to resolve relative IRI-references.
```

2020-08-28 17:02 UTC, pchampin commented on sophia/src/parser/xml_legacy.rs
> +    /// Build a new RDF XML parser with the given config.
```suggestion
    /// Build a new RDF/XML parser with the given config.
```

2020-09-16 13:50 UTC, merged

2020-09-16 13:55 UTC, pchampin commented
Finally found a moment to merge this! Thanks again @yever